<h3>CRUX Links</h3>

<h4>Official</h4>
<a href="http://crux.nu">crux.nu - The official crux page</a><br>
<a href="http://marc.theaimsgroup.com/?l=crux">Mailing list archive of the official CRUX Mailing List</a><br>
<a href="http://developer.berlios.de/projects/clc">CLC Project Overview 
and developer information</a><br>
<a href="http://crux-it.org">Italian CRUX portal</a>

<h3>httpup Port Collections</h3>
<a href="http://www.hta-bi.bfh.ch/~winkj/files/crux/jw.httpup">Johannes Winkelmann's Repository</a>
