<h3>Submit ports</h3>
you want to share your ports with other crux users?
We will soon have a solution for this :-)

<h4>Which ports are added</h4>
We usually add all ports to the unstable collection as long as they
<ul>
<li>follow the <a href="http://www.fukt.bth.se/~per/crux/doc/handbook.html#Package-Guidelines">package guidelines</a> of CRUX</li>
<li>follow the <a href="doc/pkgstd.html">package guidelines</a> of CLC</li>
<li>fit into our philosophy</li>
</ul>
Note that everyone at CLC does this volunteerily and therefore it may take some times until your port is adopted (or rejected).

